# Generated by Django 5.0.3 on 2024-03-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_rename_alt_text_news_alternative_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
