# Generated by Django 4.2.6 on 2024-01-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=50, verbose_name='Адрес Электронной Почты')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
