# Generated by Django 5.0.3 on 2024-03-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeedBack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
    ]
