# Generated by Django 5.0.3 on 2024-03-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeedBack', '0002_remove_feedback_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
