# Generated by Django 5.0.3 on 2024-03-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_news_delete_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
