# Generated by Django 5.0.3 on 2024-03-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='alt_text',
            field=models.CharField(default='image', max_length=100),
        ),
    ]
